@startjson "Forum Comments"
{
    "comments": [
        {
            "datetime_string": "2022-01-12T04:41:38Z",
            "id": 55271623,
            "num_comments": 0,
            "sticky": false,
            "title": "My login info",
            "topic": {
                "from_language_abbrev": "en",
                "from_language_name": "English",
                "id": 1,
                "name": "Duolingo"
            },
            "user": {
                "admin": false,
                "ambassador": {},
                "avatar": "//s3.amazonaws.com/duolingo-images/avatar/default_2",
                "deactivated": null,
                "flair": null,
                "has_plus": false,
                "id": 874895249,
                "mod": false,
                "username": "1C06L9H"
            },
            "user_downvoted": false,
            "user_upvoted": false,
            "votes": 0
        }
    ],
    "limits": "{\"timestamp\": \"1641861550556.589111\"}",
    "more": true,
    "page": 3,
    "subscriptions": [
        {
            "display_name": "General",
            "from_language_abbrev": "en",
            "from_language_string": "English",
            "language_abbrev": null,
            "language_string": null,
            "name": "Duolingo",
            "topic_id": 1
        },
        {
            "display_name": "English",
            "from_language_abbrev": "ja",
            "from_language_string": "Japanese",
            "language_abbrev": "en",
            "language_string": "English",
            "name": "English",
            "topic_id": 839
        },
        {
            "display_name": "Japanese",
            "from_language_abbrev": "en",
            "from_language_string": "English",
            "language_abbrev": "ja",
            "language_string": "Japanese",
            "name": "Japanese",
            "topic_id": 946
        },
        {
            "display_name": "Klingon",
            "from_language_abbrev": "en",
            "from_language_string": "English",
            "language_abbrev": "kl",
            "language_string": "Klingon",
            "name": "Klingon",
            "topic_id": 953
        }
    ],
    "user_skills": []
}
@endjson
